# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
on:
  pull_request:

name: format-suggest.yaml

permissions: read-all

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.until12apr }} # `until12apr` is a secret that contains a PAT

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format .

      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.until12apr }} # `until12apr` is a secret that contains a PAT        
          level: error
          fail_level: error
          tool_name: air
